* Archivo principal del proyecto que lee los archivos

In [ ]:
import numpy as np
import pandas as pd
from scipy import stats

In [ ]:
df_applications = pd.read_csv("./data/applications.csv")
df_applications.drop(["colmna"])
df_applications.to_csv("")
df_categories = pd.read_csv("./data/categories.csv")
df_developers = pd.read_csv("./data/developers.csv")
df_genres = pd.read_csv("./data/genres.csv")
df_platforms = pd.read_csv("./data/platforms.csv")
df_publishers = pd.read_csv("./data/publishers.csv")
df_reviews = pd.read_csv("./data/reviews.csv")
df_application_categories = pd.read_csv("./data/application_categories.csv")
df_application_developers = pd.read_csv("./data/application_developers.csv")
df_application_genres = pd.read_csv("./data/application_genres.csv")
df_application_platforms = pd.read_csv("./data/application_platforms.csv")
df_application_publishers = pd.read_csv("./data/application_publishers.csv")

/tmp/ipykernel_10983/3392862287.py:1: DtypeWarning: Columns (0: required_age) have mixed types. Specify dtype option on import or set low_memory=False.
  df_applications = pd.read_csv("./data/applications.csv")

In [ ]:
df_applications.describe()

,appid,metacritic_score,recommendations_total,mat_initial_price,mat_final_price,mat_discount_percent,mat_achievement_count
count,2.396640e+05,5299.000000,2.256000e+04,1.449230e+05,1.449230e+05,144923.000000,61401.000000
mean,2.032248e+06,74.052651,4.648429e+03,2.265139e+04,2.064869e+04,5.361916,34.411215
std,1.068241e+06,10.299116,4.642273e+04,8.571831e+05,7.796022e+05,17.769805,197.958850
min,1.000000e+01,6.000000,1.010000e+02,5.000000e+01,4.400000e+01,0.000000,0.000000
25%,1.122595e+06,69.000000,1.740000e+02,2.990000e+02,2.990000e+02,0.000000,9.000000
50%,1.993815e+06,76.000000,3.690000e+02,4.990000e+02,4.990000e+02,0.000000,17.000000
75%,2.946382e+06,81.000000,1.205250e+03,9.990000e+02,9.990000e+02,0.000000,31.000000
max,3.996190e+06,97.000000,4.661011e+06,8.990000e+07,8.910000e+07,95.000000,9821.000000

In [ ]:
df_reviews.describe()

,recommendationid,appid,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,timestamp_created,timestamp_updated,votes_up,votes_funny,weighted_vote_score,comment_count
count,1.048148e+06,1.048148e+06,1.048148e+06,1.048148e+06,1.048148e+06,1.048145e+06,1.048145e+06,8.692910e+05,1.048145e+06,1.048148e+06,1.048148e+06,1.048148e+06,1.048148e+06,1.048148e+06,1.048148e+06
mean,1.346614e+08,1.378085e+06,7.656120e+16,3.850446e+02,1.650904e+02,1.851191e+03,1.339816e+02,1.590649e+03,1.392113e+09,1.662686e+09,1.664069e+09,3.918706e+00,4.097742e+04,5.192238e-01,1.874564e-01
std,6.839674e+07,9.612286e+05,5.267878e+08,1.413666e+03,8.196265e+02,1.786494e+04,6.605448e+02,1.325358e+04,6.355876e+08,1.033218e+08,1.023927e+08,2.418852e+01,1.326620e+07,6.408803e-02,1.878285e+00
min,5.340000e+02,4.000000e+02,7.656120e+16,0.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000e+00,1.287483e+09,1.287875e+09,0.000000e+00,0.000000e+00,5.461350e-03,0.000000e+00
25%,6.787655e+07,5.682900e+05,7.656120e+16,0.000000e+00,4.000000e+00,2.100000e+01,0.000000e+00,5.100000e+01,1.517099e+09,1.587650e+09,1.590079e+09,0.000000e+00,0.000000e+00,5.000000e-01,0.000000e+00
50%,1.502615e+08,1.161580e+06,7.656120e+16,0.000000e+00,1.500000e+01,1.620000e+02,0.000000e+00,1.940000e+02,1.681467e+09,1.700199e+09,1.702176e+09,1.000000e+00,0.000000e+00,5.000000e-01,0.000000e+00
75%,2.019883e+08,1.998977e+06,7.656120e+16,2.370000e+02,5.800000e+01,7.040000e+02,0.000000e+00,6.610000e+02,1.754874e+09,1.755017e+09,1.755034e+09,3.000000e+00,0.000000e+00,5.246061e-01,0.000000e+00
max,2.037023e+08,3.977550e+06,7.656120e+16,3.975000e+04,1.832300e+04,4.309938e+06,2.014400e+04,2.030768e+06,1.757168e+09,1.757169e+09,1.757169e+09,8.270000e+03,4.294967e+09,9.954016e-01,6.660000e+02

In [ ]:
df_applications.head()

,appid,name,type,is_free,release_date,required_age,short_description,supported_languages,header_image,background,...,mat_pc_os_min,mat_pc_processor_min,mat_pc_memory_min,mat_pc_graphics_min,mat_pc_os_rec,mat_pc_processor_rec,mat_pc_memory_rec,mat_pc_graphics_rec,created_at,updated_at
0,10,Counter-Strike,game,False,2000-11-01,0,Play the world's number 1 online action game. ...,"English<strong>*</strong>, French<strong>*</st...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
1,20,Team Fortress Classic,game,False,1999-04-01,0,One of the most popular online action games of...,"English, French, German, Italian, Spanish - Sp...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
2,30,Day of Defeat,game,False,2003-05-01,0,Enlist in an intense brand of Axis vs. Allied ...,"English, French, German, Italian, Spanish - Spain",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
3,40,Deathmatch Classic,game,False,2001-06-01,0,Enjoy fast-paced multiplayer gaming with Death...,"English, French, German, Italian, Spanish - Sp...",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00
4,50,Half-Life: Opposing Force,game,False,1999-11-01,0,Return to the Black Mesa Research Facility as ...,"English, French, German, Korean",https://shared.akamai.steamstatic.com/store_it...,https://store.akamai.steamstatic.com/images/st...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2025-09-07 16:27:12.218587+00:00,2025-09-29 02:01:37.107239+00:00

In [ ]:
df_reviews.head()

,recommendationid,appid,author_steamid,author_num_games_owned,author_num_reviews,author_playtime_forever,author_playtime_last_two_weeks,author_playtime_at_review,author_last_played,language,...,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,created_at,updated_at
0,10000000,264220,76561198085405844,760,74,12.0,0.0,12.0,1.399060e+09,polish,...,True,0,1,0.459906,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
1,100001066,1006440,76561198014439859,485,234,424.0,0.0,424.0,1.632666e+09,russian,...,True,8,0,0.630770,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
2,100002344,320721,76561198048038590,0,385,0.0,0.0,NaN,0.000000e+00,german,...,False,1,0,0.523810,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
3,100002361,1604700,76561197994386273,0,3,86.0,0.0,86.0,1.632674e+09,english,...,True,3,0,0.541985,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00
4,100002504,1338560,76561198138996331,816,26,25.0,0.0,25.0,1.632639e+09,english,...,True,1,0,0.523810,0,True,False,False,2025-09-07 12:51:00.564782+00:00,2025-09-08 00:47:55.754043+00:00